# Generated by Django 5.0.3 on 2024-03-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(related_name='flights', to='airport.crew'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination')},
        ),
    ]
