# Generated by Django 5.0.3 on 2024-03-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_flight_crew_alter_route_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='position',
            field=models.CharField(choices=[('pilot', 'Pilot'), ('copilot', 'Co-Pilot'), ('flight_attendant', 'Flight Attendant'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
